spring:
  datasource:
    url: ${DATABASE_URL}
    username: admin
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    show_sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: false

security:
  jwt:
    secret-key: ${JWT_SECRET}
    duration: ${JWT_DURATION}